#######################
# Theme Customization #
#######################

title: Dreaming           # used in <title> tag & site header
author: Seoung Min Ko                       # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Studying Computer Science and trying to learn more about 'how to programming cool! I'm having fun with Web programming, Game Playing.
slogan: EveryDay!                           # used in site header, beside title
avatar: /i/myProfile.png                     # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/ksm0814            # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Home
    scheme: /home
    handle: hello       # you know, to protect you from bots. (handle and domain
    icon: /i/icon1.svg#email
  - name: Posts
    url: /posts
    icon: /i/icon1.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /
    icon: /i/icon1.svg#portfolio
  - name: GitHub
    url: https://github.com/ksm0814
    icon: /i/icon1.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icon1.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Undo
    teaser: obstacle avoid game made by visual studio with win32 api, c++
    url: http://www.sungshin.ac.kr/it/html/community/notice.html?bid=it_notice&sc_category=&sch=subject&sc_text=%B0%E6%C1%F8&page=1&idx=122971
    role: programmer
    category: programmer

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10

disqus_shortname: ksm0814.github.io
